apiVersion: v1  # Specifies the API version of the Kubernetes object
kind: Service    # Defines the type of Kubernetes object
metadata:
  name: static-web-service  # The name of the service
spec:
  type: NodePort  # Service type that exposes the service on each Node's IP at a static port
  selector:
    app: static-web  # Selector to identify the pods that this service will route traffic to
  ports:
    - port: 80       # The port that the service will expose
      targetPort: 80 # The port on the pod that the service should forward traffic to
      nodePort: 30080 # The port on each node that will forward traffic to the service
